- topic_name: "/robot2/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: BIDIRECTIONAL

- topic_name: "/robot2/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL

- topic_name: "/robot2/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: BIDIRECTIONAL

- topic_name: "/robot2/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: BIDIRECTIONAL

- topic_name: "/robot2/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: BIDIRECTIONAL

- topic_name: "/robot2/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: BIDIRECTIONAL

- topic_name: "/robot2/initialpose"
  ros_type_name: "geometry_msgs/msg/PoseWithCovarianceStamped"
  gz_type_name: "gz.msgs.PoseWithCovariance"
  direction: BIDIRECTIONAL

- topic_name: "/robot2/goal_pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "gz.msgs.Pose"
  direction: BIDIRECTIONAL
