- topic_name: "/robot1/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: BIDIRECTIONAL

- topic_name: "/robot1/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL

#TEST for bridging the other scan topic found in GZ
#- topic_name: "/robot1/scan/points"



- topic_name: "/robot1/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: BIDIRECTIONAL

- topic_name: "/robot1/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: BIDIRECTIONAL

- topic_name: "/robot1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: BIDIRECTIONAL

- topic_name: "/robot1/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: BIDIRECTIONAL

- topic_name: "/tf" #TESTING WITHOUT NAMESPACE
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: BIDIRECTIONAL

#TESTING WITHOUT BRIDGE-- Only robot_state_publishers manage tf_static
# - topic_name: "/tf_static" #TESTING WITHOUT NAMESPACE
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: BIDIRECTIONAL
#   history: KEEP_LAST
#   DEPTH: 10
#   reliabilty: RELIABLE
#   qos_profile:
#     durability: TRANSIENT_LOCAL  #DOESN'T SEEM TO WORK. tf_static has this as only publisher, needs qos compatible.

- topic_name: "/robot1/initialpose"
  ros_type_name: "geometry_msgs/msg/PoseWithCovarianceStamped"
  gz_type_name: "gz.msgs.PoseWithCovariance"
  direction: BIDIRECTIONAL

- topic_name: "/robot1/goal_pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "gz.msgs.Pose"
  direction: BIDIRECTIONAL

#global clock --> no namespace. UNIDIRECTIONAL --> ROS takes from GZ
- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS  # Gazebo → ROS
